language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
dist: precise
notifications:
  slack:
    secure: CJm0MVamIN/d/zJT9j6ybLHYGjvbjeVh3etJoo8lYRwuQy2NyWmBcNFHpE29J+9crNx8VQMCZXHipvTvg1wJVrmQalzJ64aB4+n6U7zdEDcLSOZyeibJmFLYdvvrvC9MKoqzd7PpciQAOzQGZgJhJJ56zrr9ZZLuN2UfCGbtSf1GV1UFoU72aHUAHwVoTIjlKgCkw3E2FCn29E/k+GFpEH7BN1ln1DrdJaylqRf3FBQ/pkRcfUW70V4Jr86bQ4bG7xR2TD1YWaQOwIye0oLJ4jxAjGr77uyt4D37wEzFPPjc055GGOIpJ3jMvnfCvCV09/76MZYU+u5voPfyl1mlScBzgUpZ0ZpB2kAqGldg+e8WKR4yioUALv03EWAtJyL+ZdeDSIohFThvsgiu+MB8EEpMG4dAJQrMUR/S6QAhU+Jc8fBqBBI0VE0NYYAvKzFeFLuNpw1zs66ic4A8ajHmoWBiSKl0EZvPyBeIyIjjUNmJWH92E9Lgeor5kv16BkMfgOhL+OPl7kkIwFaBOmkm8Xu9qbx/KlsgvxIcM66/VK61cAL2I2oKfoJYbdIFyuMMeME+NeKajn1qunwrQVRHlELWY3AzWkdr4x+9H0ogYAB0lzuWD35ltGsfmveTDUZ6BF1OIX1nNohrRwLUnNVq8wq4YpR5yAtqkvD3ho/ltN4=
